# https://discuss.streamlit.io/t/web-apps-keeps-on-sleeping-after-30-minutes-or-a-day-of-inactivity/97350/18?page=2
name: Reveil Automatique Streamlit

on:
  schedule:
    - cron: '0 */10 * * *'  # Runs every 10 hours

  # Pour tester le script manuellement depuis GitHub
  workflow_dispatch:

jobs:
  wake_up_app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping de l'application
        run: curl -I https://tbresto-jyyukmqvf363etkjp5krdt.streamlit.app/
